### ISSUE TITLE
Meta-ticket for having proper MVP

### ISSUE THREAD

**Issue by JuhaS** [Wiredcraft/fullpm#11]
Lets list what is needed for Wiredcraft to start using pmhub:
- [ ] Frontend polished
  - [x] basic features are working
    - load issues to board
    - link issues to github
    - show issue number and title
    - move issues from column to column
    - board state is saved automatically
    - create new board automatically
    - app works through the extension
    - have "backlog", "next", "doing", "done" labels
    - define board by url
    - app asks to login if not logged in
    - error handling on non-existing boards (or repos that user don't have access to)
  - [ ] No obvious bugs
  - [ ] Speed is acceptable
  - [ ] User experience is clear enough
  - **No advanced features needed**
- [ ] Backend
  - [ ] Reliable and supports the basic features of frontend
  - [ ] No obvious security holes
- [ ] The Chrome extension 
  - [ ] ~~Easy way to install the extension~~ (not needed for internal use)
  - [ ] Extension supporting basic use cases and no clear bugs
  - [ ] Integration tested on real servers with real repositories
- [ ] Everything integration tested in real servers and repositories
- [x] #9 pmhub running on server  (backend, frontend and extension)
  - [x] dns pointed to server
  - [x] cloudfront in front with https

Also important:
- [ ] easy way to deploy new versions to server
- [ ] Readme files up to date in repositories

If you want more clarification on any items, just come ask me.
